#!/bin/bash
./ale -game_controller internal -player_agent self_detection_agent -num_block_per_row 16 -num_block_per_col 21 -display_screen true -end_training_time 5000 -eval_frames 1000 ./roms/enduro.bin

