MODULE := src/emucore

MODULE_OBJS := \
	src/emucore/AtariVox.o \
	src/emucore/Booster.o \
	src/emucore/Cart2K.o \
	src/emucore/Cart3F.o \
	src/emucore/Cart3E.o \
	src/emucore/Cart4A50.o \
	src/emucore/Cart4K.o \
	src/emucore/CartAR.o \
	src/emucore/CartCV.o \
	src/emucore/Cart.o \
	src/emucore/CartDPC.o \
	src/emucore/CartE0.o \
	src/emucore/CartE7.o \
	src/emucore/CartF4.o \
	src/emucore/CartF4SC.o \
	src/emucore/CartF6.o \
	src/emucore/CartF6SC.o \
	src/emucore/CartF8.o \
	src/emucore/CartF8SC.o \
	src/emucore/CartFASC.o \
	src/emucore/CartFE.o \
	src/emucore/CartMB.o \
	src/emucore/CartMC.o \
	src/emucore/CartUA.o \
	src/emucore/Cart0840.o \
	src/emucore/Console.o \
	src/emucore/Control.o \
	src/emucore/Deserializer.o \
	src/emucore/Driving.o \
	src/emucore/Event.o \
	src/emucore/FSNode.o \
	src/emucore/Joystick.o \
	src/emucore/Keyboard.o \
	src/emucore/M6532.o \
	src/emucore/MD5.o \
	src/emucore/MediaSrc.o \
	src/emucore/OSystem.o \
	src/emucore/Paddles.o \
	src/emucore/Props.o \
	src/emucore/PropsSet.o \
	src/emucore/Random.o \
	src/emucore/Serializer.o \
	src/emucore/Settings.o \
	src/emucore/SpeakJet.o \
	src/emucore/Switches.o \
	src/emucore/TIA.o \
	src/emucore/TIASnd.o \
	src/emucore/unzip.o \

MODULE_HEADERS := \
	src/emucore/AtariVox.hxx \
	src/emucore/Booster.hxx \
	src/emucore/Cart2K.hxx \
	src/emucore/Cart3F.hxx \
	src/emucore/Cart3E.hxx \
	src/emucore/Cart4A50.hxx \
	src/emucore/Cart4K.hxx \
	src/emucore/CartAR.hxx \
	src/emucore/CartCV.hxx \
	src/emucore/Cart.hxx \
	src/emucore/CartDPC.hxx \
	src/emucore/CartE0.hxx \
	src/emucore/CartE7.hxx \
	src/emucore/CartF4.hxx \
	src/emucore/CartF4SC.hxx \
	src/emucore/CartF6.hxx \
	src/emucore/CartF6SC.hxx \
	src/emucore/CartF8.hxx \
	src/emucore/CartF8SC.hxx \
	src/emucore/CartFASC.hxx \
	src/emucore/CartFE.hxx \
	src/emucore/CartMB.hxx \
	src/emucore/CartMC.hxx \
	src/emucore/CartUA.hxx \
	src/emucore/Cart0840.hxx \
	src/emucore/Console.hxx \
	src/emucore/Control.hxx \
	src/emucore/Deserializer.hxx \
	src/emucore/Driving.hxx \
	src/emucore/Event.hxx \
	src/emucore/FSNode.hxx \
	src/emucore/Joystick.hxx \
	src/emucore/Keyboard.hxx \
	src/emucore/M6532.hxx \
	src/emucore/MD5.hxx \
	src/emucore/MediaSrc.hxx \
	src/emucore/OSystem.hxx \
	src/emucore/Paddles.hxx \
	src/emucore/Props.hxx \
	src/emucore/PropsSet.hxx \
	src/emucore/Random.hxx \
	src/emucore/Serializer.hxx \
	src/emucore/Settings.hxx \
	src/emucore/SpeakJet.hxx \
	src/emucore/Switches.hxx \
	src/emucore/TIA.hxx \
	src/emucore/TIASnd.hxx \
	src/emucore/unzip.h \

MODULE_SOURCES := \
	src/emucore/AtariVox.cxx \
	src/emucore/Booster.cxx \
	src/emucore/Cart2K.cxx \
	src/emucore/Cart3F.cxx \
	src/emucore/Cart3E.cxx \
	src/emucore/Cart4A50.cxx \
	src/emucore/Cart4K.cxx \
	src/emucore/CartAR.cxx \
	src/emucore/CartCV.cxx \
	src/emucore/Cart.cxx \
	src/emucore/CartDPC.cxx \
	src/emucore/CartE0.cxx \
	src/emucore/CartE7.cxx \
	src/emucore/CartF4.cxx \
	src/emucore/CartF4SC.cxx \
	src/emucore/CartF6.cxx \
	src/emucore/CartF6SC.cxx \
	src/emucore/CartF8.cxx \
	src/emucore/CartF8SC.cxx \
	src/emucore/CartFASC.cxx \
	src/emucore/CartFE.cxx \
	src/emucore/CartMB.cxx \
	src/emucore/CartMC.cxx \
	src/emucore/CartUA.cxx \
	src/emucore/Cart0840.cxx \
	src/emucore/Console.cxx \
	src/emucore/Control.cxx \
	src/emucore/Deserializer.cxx \
	src/emucore/Driving.cxx \
	src/emucore/Event.cxx \
	src/emucore/FSNode.cxx \
	src/emucore/Joystick.cxx \
	src/emucore/Keyboard.cxx \
	src/emucore/M6532.cxx \
	src/emucore/MD5.cxx \
	src/emucore/MediaSrc.cxx \
	src/emucore/OSystem.cxx \
	src/emucore/Paddles.cxx \
	src/emucore/Props.cxx \
	src/emucore/PropsSet.cxx \
	src/emucore/Random.cxx \
	src/emucore/Serializer.cxx \
	src/emucore/Settings.cxx \
	src/emucore/SpeakJet.cxx \
	src/emucore/Switches.cxx \
	src/emucore/TIA.cxx \
	src/emucore/TIASnd.cxx \
	src/emucore/unzip.c \

MODULE_DIRS += \
	src/emucore

# Include common rules 
include $(srcdir)/common.rules
